add_newline = false
command_timeout = 1000

format = "$directory$git_branch$git_status$character"

[character]
success_symbol = "[âœ](bold #9ccfd8)"
error_symbol = "[âœ](bold #eb6f92)"

[directory]
style = "bold #eb6f92"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "î‚  "
style = "bold #3e8fb0"

[git_status]
style = "bold #ea9a97"
deleted = "âœ˜"
modified = "*"
staged = "S"
renamed = "Â»"
untracked = "?"
stashed = "$"
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"
conflicted = 'ğŸ³'
up_to_date = 'âœ“'

[nix_shell]
disabled = false
impure_msg = '[impure shell](bold #9ccfd8)'
pure_msg = '[pure shell](bold #9ccfd8)'
unknown_msg = '[unknown shell](bold #9ccfd8)'
format = 'via [â˜ƒï¸ $state( \($name\))](bold #9ccfd8) '
